### ISSUE TITLE
Add nodeport/ingress service options

### ISSUE THREAD

**Issue by ddieruf** [LangStream/charts#1]
Currently 'control-plane-deployment.yaml' gives the primary container the following option for port numbering:

```
ports:
  - name: http
    containerPort: {{ .Values.controlPlane.service.port }}
    protocol: TCP
```

The 'control-plane-service.yaml' uses the same port value to set the service. 

```
spec:
  type: {{ .Values.controlPlane.service.type }}
  ports:
    - port: {{ .Values.controlPlane.service.port }}
      targetPort: http
      protocol: TCP
      name: http
```

If I set the 'type' to NodePort, but can't set a NodePort value then K8s will choose one for me. But I have no way of setting the container port so it will default to "8090". Which renders the service unhealthy and the control plane pod inaccessible.
